# Generated by Django 3.1.4 on 2020-12-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=20)),
                ('p_difficulty', models.CharField(max_length=20)),
                ('p_wpm', models.PositiveIntegerField()),
                ('p_floor', models.PositiveIntegerField()),
            ],
        ),
    ]
